// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0cH0Fj58SZJH78OBfH3CjIB8kBcYQv-s',
    appId: '1:474421880721:web:76493bc85ade0315fedc30',
    messagingSenderId: '474421880721',
    projectId: 'chat-app-19148',
    authDomain: 'chat-app-19148.firebaseapp.com',
    storageBucket: 'chat-app-19148.appspot.com',
    measurementId: 'G-EQY1VW7LHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfxnfWGPA-VqEwszT2P7R6ZeysPC6T-k',
    appId: '1:474421880721:android:b862560073c3e782fedc30',
    messagingSenderId: '474421880721',
    projectId: 'chat-app-19148',
    storageBucket: 'chat-app-19148.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrlyBAvOdr2inDl8G5cKD348_iuUOvGqA',
    appId: '1:474421880721:ios:7847169d6b15e699fedc30',
    messagingSenderId: '474421880721',
    projectId: 'chat-app-19148',
    storageBucket: 'chat-app-19148.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrlyBAvOdr2inDl8G5cKD348_iuUOvGqA',
    appId: '1:474421880721:ios:7847169d6b15e699fedc30',
    messagingSenderId: '474421880721',
    projectId: 'chat-app-19148',
    storageBucket: 'chat-app-19148.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0cH0Fj58SZJH78OBfH3CjIB8kBcYQv-s',
    appId: '1:474421880721:web:6cb7134c290b6600fedc30',
    messagingSenderId: '474421880721',
    projectId: 'chat-app-19148',
    authDomain: 'chat-app-19148.firebaseapp.com',
    storageBucket: 'chat-app-19148.appspot.com',
    measurementId: 'G-K8G30700TE',
  );
}
